version: '3.8'

services:
  herrold:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: herrold-app
    ports:
      - "${PORT:-3005}:3005"
    environment:
      - NODE_ENV=production
      - PORT=${PORT:-3005}
      # Handraise configuration
      - HANDRAISE_URL=${HANDRAISE_URL}
      - HANDRAISE_USERNAME=${HANDRAISE_USERNAME}
      - HANDRAISE_PASSWORD=${HANDRAISE_PASSWORD}
      # Optional email configuration
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_SECURE=${SMTP_SECURE}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - EMAIL_FROM=${EMAIL_FROM}
      - EMAIL_TO=${EMAIL_TO}
      # Optional webhook configuration
      - WEBHOOK_URL=${WEBHOOK_URL}
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
      # Debug settings
      - HEADED_MODE=${HEADED_MODE:-false}
      - SLOW_MO=${SLOW_MO:-0}
      - DEVTOOLS=${DEVTOOLS:-false}
      - DEBUG_TIMEOUT=${DEBUG_TIMEOUT:-120000}
    volumes:
      # Mount test artifacts directory for persistence
      - ./test-artifacts:/app/test-artifacts
      # Mount .env file if you prefer file-based config
      - ./.env:/app/.env:ro
    restart: unless-stopped
    networks:
      - herrold-network
    # Resource limits for container
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '1'
          memory: 2G

  # Optional: Add a reverse proxy for production
  # nginx:
  #   image: nginx:alpine
  #   container_name: herrold-nginx
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./ssl:/etc/nginx/ssl:ro
  #   depends_on:
  #     - herrold
  #   networks:
  #     - herrold-network

networks:
  herrold-network:
    driver: bridge